const ats = [
    {
        "flight_number": "1164",
        "carrier_code": "UA",
        "carrier_name": "United Airlines",
        "flight_type": "RON",
        "eqp_type": "Boeing 737MAX 8 Passenger",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 07:30:00",
        "sch_arr_time": "01-MAR-24 07:30:00",
        "dep_port_code": "SFO",
        "dep_city_code": "San Francisco",
        "dep_country_code": "US",
        "arr_port_code": "YYZ",
        "arr_city_code": "Toronto",
        "arr_country_code": "CA",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "737 MAX 8",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UA-1",
        "service_id": 27566937,
        "created_by": 1234,
        "creation_date": "2024-02-29T08:03:34Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-02-29T08:03:34Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-02-29T00:00:00Z"
    },
    {
        "flight_number": "1345",
        "carrier_code": "UA",
        "carrier_name": "United Airlines",
        "flight_type": "ORIG",
        "eqp_type": "Boeing 737-800 Passenger",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 06:10:00",
        "sch_arr_time": "01-MAR-24 06:10:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "IAH",
        "arr_city_code": "Houston",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "737-800",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UA-1",
        "service_id": 27567700,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3634",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "ORIG",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 06:15:00",
        "sch_arr_time": "01-MAR-24 06:15:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "IAD",
        "arr_city_code": "Washington",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567701,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "565",
        "carrier_code": "UA",
        "carrier_name": "United Airlines",
        "flight_type": "ORIG",
        "eqp_type": "Boeing 737-800 Passenger",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 06:30:00",
        "sch_arr_time": "01-MAR-24 06:30:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "SFO",
        "arr_city_code": "San Francisco",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "737-800",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UA-1",
        "service_id": 27567702,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3640",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "ORIG",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 06:52:00",
        "sch_arr_time": "01-MAR-24 06:52:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "ORD",
        "arr_city_code": "Chicago",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567703,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3435",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "ORIG",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 07:30:00",
        "sch_arr_time": "01-MAR-24 07:30:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "EWR",
        "arr_city_code": "New York",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567704,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "423",
        "carrier_code": "UA",
        "carrier_name": "United Airlines",
        "flight_type": "ORIG",
        "eqp_type": "Airbus A320",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 07:55:00",
        "sch_arr_time": "01-MAR-24 07:55:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "DEN",
        "arr_city_code": "Denver",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "A320",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UA-1",
        "service_id": 27567705,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "1538",
        "carrier_code": "UA",
        "carrier_name": "United Airlines",
        "flight_type": "ORIG",
        "eqp_type": "Boeing 737MAX 8 Passenger",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 09:00:00",
        "sch_arr_time": "01-MAR-24 09:00:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "ORD",
        "arr_city_code": "Chicago",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "737 MAX 8",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UA-1",
        "service_id": 27567706,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3701",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 170",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 09:30:00",
        "sch_arr_time": "01-MAR-24 08:47:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "EWR",
        "arr_city_code": "New York",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3553",
        "aircraft_type": "E170",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567707,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3636",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "ORIG",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 10:00:00",
        "sch_arr_time": "01-MAR-24 10:00:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "IAD",
        "arr_city_code": "Washington",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567708,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3648",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 10:45:00",
        "sch_arr_time": "01-MAR-24 09:58:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "EWR",
        "arr_city_code": "New York",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3522",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567709,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "5578",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 11:00:00",
        "sch_arr_time": "01-MAR-24 10:03:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "ORD",
        "arr_city_code": "Chicago",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "5450",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567710,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3649",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 12:45:00",
        "sch_arr_time": "01-MAR-24 11:50:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "EWR",
        "arr_city_code": "New York",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3555",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567711,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3637",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 14:45:00",
        "sch_arr_time": "01-MAR-24 13:46:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "IAD",
        "arr_city_code": "Washington",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3400",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567712,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3543",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 15:00:00",
        "sch_arr_time": "01-MAR-24 13:55:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "ORD",
        "arr_city_code": "Chicago",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3478",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567713,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3651",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 15:30:00",
        "sch_arr_time": "01-MAR-24 14:47:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "EWR",
        "arr_city_code": "New York",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3523",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567714,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "5330",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 15:50:00",
        "sch_arr_time": "01-MAR-24 14:20:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "IAH",
        "arr_city_code": "Houston",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "4749",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567715,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "568",
        "carrier_code": "UA",
        "carrier_name": "United Airlines",
        "flight_type": "TURN",
        "eqp_type": "Airbus A320",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 16:00:00",
        "sch_arr_time": "01-MAR-24 15:02:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "DEN",
        "arr_city_code": "Denver",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "1874",
        "aircraft_type": "A320",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UA-1",
        "service_id": 27567716,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "5599",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 17:30:00",
        "sch_arr_time": "01-MAR-24 16:25:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "ORD",
        "arr_city_code": "Chicago",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "5453",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567717,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3460",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 17:40:00",
        "sch_arr_time": "01-MAR-24 16:52:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "EWR",
        "arr_city_code": "New York",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3556",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567718,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3535",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 18:40:00",
        "sch_arr_time": "01-MAR-24 17:55:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "EWR",
        "arr_city_code": "New York",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3557",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567719,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3513",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 19:40:00",
        "sch_arr_time": "01-MAR-24 18:57:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "IAD",
        "arr_city_code": "Washington",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3671",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567720,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "5580",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "TURN",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 21:00:00",
        "sch_arr_time": "01-MAR-24 19:57:00",
        "dep_port_code": "YYZ",
        "dep_city_code": "Toronto",
        "dep_country_code": "CA",
        "arr_port_code": "ORD",
        "arr_city_code": "Chicago",
        "arr_country_code": "US",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "lnkd_flight_number": "3504",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27567721,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:23Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:23Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3434",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "RON",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 21:52:00",
        "sch_arr_time": "01-MAR-24 21:52:00",
        "dep_port_code": "EWR",
        "dep_city_code": "New York",
        "dep_country_code": "US",
        "arr_port_code": "YYZ",
        "arr_city_code": "Toronto",
        "arr_country_code": "CA",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27568222,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:26Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:26Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3593",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "RON",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 23:59:00",
        "sch_arr_time": "01-MAR-24 23:59:00",
        "dep_port_code": "ORD",
        "dep_city_code": "Chicago",
        "dep_country_code": "US",
        "arr_port_code": "YYZ",
        "arr_city_code": "Toronto",
        "arr_country_code": "CA",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27568223,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:26Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:26Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "5462",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "RON",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 18:42:00",
        "sch_arr_time": "01-MAR-24 18:42:00",
        "dep_port_code": "ORD",
        "dep_city_code": "Chicago",
        "dep_country_code": "US",
        "arr_port_code": "YYZ",
        "arr_city_code": "Toronto",
        "arr_country_code": "CA",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27568224,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:26Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:26Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "313",
        "carrier_code": "UA",
        "carrier_name": "United Airlines",
        "flight_type": "RON",
        "eqp_type": "Boeing 737-800 Passenger",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 22:37:00",
        "sch_arr_time": "01-MAR-24 22:37:00",
        "dep_port_code": "IAH",
        "dep_city_code": "Houston",
        "dep_country_code": "US",
        "arr_port_code": "YYZ",
        "arr_city_code": "Toronto",
        "arr_country_code": "CA",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "737-800",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UA-1",
        "service_id": 27568225,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:26Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:26Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "3525",
        "carrier_code": "UAX",
        "carrier_name": "United Express",
        "flight_type": "RON",
        "eqp_type": "Embraer 175 (Enhanced Winglets)",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 23:46:00",
        "sch_arr_time": "01-MAR-24 23:46:00",
        "dep_port_code": "IAD",
        "dep_city_code": "Washington",
        "dep_country_code": "US",
        "arr_port_code": "YYZ",
        "arr_city_code": "Toronto",
        "arr_country_code": "CA",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "E175",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UAX-1",
        "service_id": 27568226,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:26Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:26Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "265",
        "carrier_code": "UA",
        "carrier_name": "United Airlines",
        "flight_type": "RON",
        "eqp_type": "Boeing 737-800 Passenger",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 21:25:00",
        "sch_arr_time": "01-MAR-24 21:25:00",
        "dep_port_code": "ORD",
        "dep_city_code": "Chicago",
        "dep_country_code": "US",
        "arr_port_code": "YYZ",
        "arr_city_code": "Toronto",
        "arr_country_code": "CA",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "737-800",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UA-1",
        "service_id": 27568227,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:26Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:26Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    },
    {
        "flight_number": "1094",
        "carrier_code": "UA",
        "carrier_name": "United Airlines",
        "flight_type": "RON",
        "eqp_type": "Airbus A320",
        "flight_status": "Open",
        "sch_dep_time": "01-MAR-24 22:45:00",
        "sch_arr_time": "01-MAR-24 22:45:00",
        "dep_port_code": "DEN",
        "dep_city_code": "Denver",
        "dep_country_code": "US",
        "arr_port_code": "YYZ",
        "arr_city_code": "Toronto",
        "arr_country_code": "CA",
        "number_of_sch": 22,
        "ats_station": "YYZ249",
        "aircraft_type": "A320",
        "international": "Y",
        "flight_category": "Passenger",
        "account_number": "UA-1",
        "service_id": 27568229,
        "created_by": 1234,
        "creation_date": "2024-03-01T08:00:26Z",
        "last_updated_by": 1234,
        "last_update_date": "2024-03-01T08:00:26Z",
        "grace_period": 0,
        "rate_based_on": "ALL",
        "body_type": "N",
        "run_date": "2024-03-01T00:00:00Z"
    }
]
    
const agione = [
    {
        "workdayTransactions": null,
        "carrierId": 19,
        "carrier": null,
        "stationId": 30,
        "station": null,
        "customerId": 878,
        "customer": null,
        "acTypeId": 2,
        "acType": null,
        "operationTypeId": 12,
        "operationType": null,
        "statusId": 4,
        "workOrderStatus": null,
        "inboundOriginAirportId": 62,
        "inboundOriginAirport": null,
        "outboundDestinationAirportId": 107,
        "outboundDestinationAirport": null,
        "contractId": 596,
        "contract": null,
        "responsibleId": null,
        "responsible": null,
        "flightStatusId": 15,
        "flightStatus": null,
        "scheduleStatusId": null,
        "scheduleStatus": null,
        "workOrderItems": [],
        "gateId": null,
        "gate": null,
        "companyId": 34,
        "company": null,
        "businessUnitId": 8,
        "businessUnit": null,
        "schedulerId": null,
        "scheduler": null,
        "adHoc": false,
        "customCustomer": false,
        "inboundCustomFlightNumber": null,
        "needToBePosted": false,
        "customCustomerName": null,
        "remark": null,
        "delay": [],
        "safetyMessage": null,
        "customerSignature": null,
        "customerName": null,
        "customerTitle": null,
        "representativeSignature": null,
        "representativeName": null,
        "representativeTitle": null,
        "scheduleDate": "2024-03-01T00:08:00",
        "date": null,
        "referenceId": "YYZ-CM470-240229",
        "inboundFlightNumber": "CM470",
        "inboundTailNumber": null,
        "inboundScheduledArrival": "2024-03-01T05:08:00",
        "inboundBlockIn": "2024-03-07T05:08:00",
        "estimatedOnUtc": null,
        "inboundCargoTotalUldsUnloaded": null,
        "inboundCargoBulkUnloaded": null,
        "outboundFlightNumber": "CM470",
        "outboundFaFlightId": null,
        "outboundTailNumber": null,
        "outboundScheduledDeparture": null,
        "outboundBlockOut": null,
        "estimatedOffUtc": null,
        "calendar": {
            "title": "CM470",
            "gate": "176",
            "sta": "0508",
            "std": ""
        },
        "outboundCustomFlightNumber": null,
        "outboundCargoTotalUldsLoaded": null,
        "outboundCargoBulkLoaded": null,
        "cancellationNoticeTime": null,
        "ourDelay": null,
        "delayComment": null,
        "cargoTotalKilosLoaded": null,
        "cargoTotalKilosUnloaded": null,
        "preFlightNumber": "CM470",
        "faFlightId": "CMP470-1709077200-schedule-369p",
        "faFlightStatus": "Scheduled",
        "comments": 0,
        "sta": "05:08:00",
        "std": null,
        "inboundGateArrival": "176",
        "outboundGateDeparture": "110",
        "cancellationType": null,
        "timezone": "America/Toronto",
        "flightPosition": null,
        "isReportable": true,
        "transactions": null,
        "flightStatusColor": null,
        "id": 112158,
        "createdAt": "2024-02-29T01:07:13.2776114",
        "updatedAt": "2024-03-07T14:54:38.8877519",
        "deletedAt": null,
        "restoredAt": null,
        "createdBy": null,
        "updatedBy": 30479,
        "deletedBy": null,
        "restoredBy": null,
        "externalId": "passfasync",
        "offlineId": null,
        "options": null,
        "isRevisionable": true,
        "forceDelete": false,
        "defaultInclude": "customer,workOrderItems,workOrderItems.workOrderItemAttributes,gate,flightStatus,station.airport",
        "searchableFields": "id,reference_id,company_id,business_unit_id",
        "fileFormats": null
    },
    {
        "workdayTransactions": null,
        "carrierId": 19,
        "carrier": null,
        "stationId": 30,
        "station": null,
        "customerId": 878,
        "customer": null,
        "acTypeId": 2,
        "acType": null,
        "operationTypeId": 20,
        "operationType": null,
        "statusId": 4,
        "workOrderStatus": null,
        "inboundOriginAirportId": 107,
        "inboundOriginAirport": null,
        "outboundDestinationAirportId": 62,
        "outboundDestinationAirport": null,
        "contractId": 596,
        "contract": null,
        "responsibleId": null,
        "responsible": null,
        "flightStatusId": 15,
        "flightStatus": null,
        "scheduleStatusId": null,
        "scheduleStatus": null,
        "workOrderItems": [],
        "gateId": null,
        "gate": null,
        "companyId": 34,
        "company": null,
        "businessUnitId": 8,
        "businessUnit": null,
        "schedulerId": null,
        "scheduler": null,
        "adHoc": false,
        "customCustomer": false,
        "inboundCustomFlightNumber": null,
        "needToBePosted": false,
        "customCustomerName": null,
        "remark": null,
        "delay": [],
        "safetyMessage": null,
        "customerSignature": null,
        "customerName": null,
        "customerTitle": null,
        "representativeSignature": null,
        "representativeName": null,
        "representativeTitle": null,
        "scheduleDate": "2024-03-01T07:54:00",
        "date": null,
        "referenceId": "YYZ-CM471-240229",
        "inboundFlightNumber": "CM471",
        "inboundTailNumber": null,
        "inboundScheduledArrival": null,
        "inboundBlockIn": null,
        "estimatedOnUtc": null,
        "inboundCargoTotalUldsUnloaded": null,
        "inboundCargoBulkUnloaded": null,
        "outboundFlightNumber": "CM471",
        "outboundFaFlightId": "CMP471-1709125392-schedule-1532p",
        "outboundTailNumber": null,
        "outboundScheduledDeparture": "2024-03-01T12:54:00",
        "outboundBlockOut": null,
        "estimatedOffUtc": null,
        "calendar": {
            "title": "CM471",
            "gate": "E76",
            "sta": "",
            "std": "1254"
        },
        "outboundCustomFlightNumber": null,
        "outboundCargoTotalUldsLoaded": null,
        "outboundCargoBulkLoaded": null,
        "cancellationNoticeTime": null,
        "ourDelay": null,
        "delayComment": null,
        "cargoTotalKilosLoaded": null,
        "cargoTotalKilosUnloaded": null,
        "preFlightNumber": "CM471",
        "faFlightId": "CMP471-1709125392-schedule-1532p",
        "faFlightStatus": "Scheduled",
        "comments": 0,
        "sta": null,
        "std": "12:54:00",
        "inboundGateArrival": "216",
        "outboundGateDeparture": "E76",
        "cancellationType": null,
        "timezone": "America/Toronto",
        "flightPosition": null,
        "isReportable": true,
        "transactions": [
            {
                "work_order_id": 112291,
                "workOrder": null,
                "contract_line_id": null,
                "contractLine": null,
                "product_id": 399,
                "product": null,
                "transaction_id": null,
                "quantity": 1,
                "posted_at": null,
                "dateTransaction": null,
                "ammount": 0,
                "is_reportable": true,
                "status": 0,
                "id": 908615,
                "created_at": "2024-03-07T19:55:23.2001137",
                "updated_at": null,
                "deleted_at": null,
                "restored_at": null,
                "created_by": null,
                "updated_by": null,
                "deleted_by": null,
                "restored_by": null,
                "external_id": null,
                "offline_id": null,
                "options": null,
                "is_revisionable": true,
                "force_delete": false,
                "dynamic_parameters": {},
                "default_include": "",
                "searchable_fields": "",
                "file_formats": null
            }
        ],
        "flightStatusColor": null,
        "id": 112291,
        "createdAt": "2024-02-29T09:07:12.4083397",
        "updatedAt": "2024-03-07T14:55:22.9697867",
        "deletedAt": null,
        "restoredAt": null,
        "createdBy": null,
        "updatedBy": 30479,
        "deletedBy": null,
        "restoredBy": null,
        "externalId": "passfasync",
        "offlineId": null,
        "options": null,
        "isRevisionable": true,
        "forceDelete": false,
        "defaultInclude": "customer,workOrderItems,workOrderItems.workOrderItemAttributes,gate,flightStatus,station.airport",
        "searchableFields": "id,reference_id,company_id,business_unit_id",
        "fileFormats": null
    },
    {
        "workdayTransactions": null,
        "carrierId": 46,
        "carrier": null,
        "stationId": 30,
        "station": null,
        "customerId": null,
        "customer": null,
        "acTypeId": 28,
        "acType": null,
        "operationTypeId": 7,
        "operationType": null,
        "statusId": 5,
        "workOrderStatus": null,
        "inboundOriginAirportId": 191,
        "inboundOriginAirport": null,
        "outboundDestinationAirportId": 191,
        "outboundDestinationAirport": null,
        "contractId": null,
        "contract": null,
        "responsibleId": null,
        "responsible": null,
        "flightStatusId": 15,
        "flightStatus": null,
        "scheduleStatusId": null,
        "scheduleStatus": null,
        "workOrderItems": [],
        "gateId": null,
        "gate": null,
        "companyId": 34,
        "company": null,
        "businessUnitId": 8,
        "businessUnit": null,
        "schedulerId": null,
        "scheduler": null,
        "adHoc": null,
        "customCustomer": false,
        "inboundCustomFlightNumber": false,
        "needToBePosted": false,
        "customCustomerName": null,
        "remark": null,
        "delay": null,
        "safetyMessage": null,
        "customerSignature": null,
        "customerName": null,
        "customerTitle": null,
        "representativeSignature": null,
        "representativeName": null,
        "representativeTitle": null,
        "scheduleDate": "2024-03-01T15:02:00",
        "date": null,
        "referenceId": "YYZ-UA1874-240229",
        "inboundFlightNumber": "UA1874",
        "inboundTailNumber": "N455UA",
        "inboundScheduledArrival": "2024-03-01T20:02:00",
        "inboundBlockIn": null,
        "estimatedOnUtc": null,
        "inboundCargoTotalUldsUnloaded": null,
        "inboundCargoBulkUnloaded": null,
        "outboundFlightNumber": "UA568",
        "outboundFaFlightId": "UAL568-1709100913-fa-909p",
        "outboundTailNumber": "N455UA",
        "outboundScheduledDeparture": "2024-03-01T21:00:00",
        "outboundBlockOut": null,
        "estimatedOffUtc": null,
        "calendar": {
            "title": "UA1874/UA568",
            "gate": "B16/F98",
            "sta": "2002",
            "std": "2100"
        },
        "outboundCustomFlightNumber": false,
        "outboundCargoTotalUldsLoaded": null,
        "outboundCargoBulkLoaded": null,
        "cancellationNoticeTime": null,
        "ourDelay": null,
        "delayComment": null,
        "cargoTotalKilosLoaded": null,
        "cargoTotalKilosUnloaded": null,
        "preFlightNumber": "UA1874",
        "faFlightId": "UAL1874-1709059970-fa-1509p",
        "faFlightStatus": "Scheduled",
        "comments": 0,
        "sta": "20:02:00",
        "std": "21:00:00",
        "inboundGateArrival": "B16",
        "outboundGateDeparture": "F98",
        "cancellationType": null,
        "timezone": "America/Toronto",
        "flightPosition": null,
        "isReportable": true,
        "transactions": null,
        "flightStatusColor": null,
        "id": 112615,
        "createdAt": "2024-02-29T15:07:30.3360422",
        "updatedAt": "2024-03-01T15:11:02.2448599",
        "deletedAt": null,
        "restoredAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "restoredBy": null,
        "externalId": "passfasync",
        "offlineId": null,
        "options": null,
        "isRevisionable": true,
        "forceDelete": false,
        "defaultInclude": "customer,workOrderItems,workOrderItems.workOrderItemAttributes,gate,flightStatus,station.airport",
        "searchableFields": "id,reference_id,company_id,business_unit_id",
        "fileFormats": null
    }
]

module.exports = { ats, agione }