name: Deploy to FTPS Server

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm i
      
    - name: Deploy via SFTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTPS_SERVER }}
        user: ${{ secrets.FTPS_USERNAME }}
        pass: ${{ secrets.FTPS_PASSWORD }}
        localDir: "./"
        remoteDir: "/site/wwwroot/"
        options: "--verbose --delete --exclude-glob=.git* --exclude-glob=.github/ --exclude-glob=README.md --exclude-glob=.env.production --exclude-glob=.env.example --exclude-glob=logs/ --exclude-glob=tmp/ --exclude-glob=*.log --exclude-glob=.DS_Store --exclude-glob=Thumbs.db --exclude-glob=ecosystem.config.json"
        
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Application should be accessible at your server."
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi