name: Deploy to FTPS Server

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm i
      
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'airportbutler-uscent-webapp01'
        package: .
        publish-profile: ${{
          github.ref == 'refs/heads/main' && secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DC044CCF282D4274B74ECD6D309C7730 ||
          github.ref == 'refs/heads/staging' && secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CA8DCC5878C944188F13136D96B1FA8E ||
          github.ref == 'refs/heads/dev' && secrets.AZURE_DEPLOY_TOKEN_DEV ||
          github.ref == 'refs/heads/localhost' && secrets.AZURE_DEPLOY_TOKEN_LOCAL}}
        
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Application should be accessible at your server."
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi